
spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alumni?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  mail:
    host: smtp.naver.com
    port: 465
    username: soeun8636@naver.com
    password: soeun8520!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

cloud:
  aws:
    s3:
      bucket: alumni-profile-image
    credentials:
      access-key: AKIAQGVHDCEMMZHID6U6
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR